name: flutter_qiita_client
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  dio: ^5.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_hooks: ^0.18.5+1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.2.0
  http: ^0.13.5
  json_annotation: ^4.8.0
  retrofit: ^4.0.1
  visibility_detector: ^0.3.3

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  golden_toolkit: ^0.14.0
  json_serializable: ^6.6.1
  mockito: ^5.3.2
  retrofit_generator: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
  fonts:
   - family: Inter
     fonts:
       - asset: assets/fonts/Inter-Thin.ttf
       - asset: assets/fonts/Inter-SemiBold.ttf
       - asset: assets/fonts/Inter-Regular.ttf
       - asset: assets/fonts/Inter-Medium.ttf
       - asset: assets/fonts/Inter-Light.ttf
       - asset: assets/fonts/Inter-ExtraLight.ttf
       - asset: assets/fonts/Inter-ExtraBold.ttf
       - asset: assets/fonts/Inter-Bold.ttf
       - asset: assets/fonts/Inter-Black.ttf
   - family: Noto Sans JP
     fonts:
       - asset: assets/fonts/NotoSansJP-Thin.ttf
       - asset: assets/fonts/NotoSansJP-Regular.ttf
       - asset: assets/fonts/NotoSansJP-Medium.ttf
       - asset: assets/fonts/NotoSansJP-Light.ttf
       - asset: assets/fonts/NotoSansJP-Bold.ttf
       - asset: assets/fonts/NotoSansJP-Black.ttf
