name: Flutter CI

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.3'

      - name: Install dependencies
        run: flutter pub get

      - name: touch file
        run: touch .env

      - name: Run Flutter tests and generate coverage
        run: flutter test --coverage

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Comment PR with test coverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COVERAGE=$(cat coverage/lcov.info)  # Flutter generates lcov.info file by default
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          COMMENT="## Test Coverage Report\n\`\`\`\n$COVERAGE\n\`\`\`"
          echo $COMMENT
          echo $COMMENT > comment.txt
          gh pr comment $PR_NUMBER --body-file comment.txt
