name: Visual Regression Test

on:
  pull_request:
    types: [opened, closed]
    paths:
      - '**.dart'
      - '**/pubspec.yaml'
      - '**/pubspec.lock'
      - '**/assets/**'

  issue_comment:
    types: [created]

jobs:

  # Base branch のスクリーンショットを取得
  reg-suit-prepare:
    name: Prepare base branch screenshots
    if: | 
      (github.event.action == 'opened') ||
      (github.event.issue.pull_request && github.event.comment.body == '/vrt')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}
          fetch-depth: 0

      - name: Check commit hash
        id: commithash
        run: echo "hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      # Hash 値のスクリーンショットのキャッシュがあれば使う
      - name: Restore reg-suit screenshots
        uses: actions/cache@v3
        with:
          path: .reg/
          key: reg-${{ steps.commithash.outputs.hash }}

      # スクリーンショット存在チェック
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@20b4d2e596410855db8f9ca21e96fbe18e12930b # v2.0.0
        with:
          files: '.reg/'

      # スクリーンショットがなければ生成する
      - name: Use Node.js v16
        if: steps.check_files.outputs.files_exists == 'false'
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Setup Flutter
        if: steps.check_files.outputs.files_exists == 'false'
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.2'
      - name: run reg-suit
        if: steps.check_files.outputs.files_exists == 'false'
        run: |
          flutter pub get
          touch .env
          flutter test --update-goldens --tags=golden
          mkdir -p screenshots/
          cp -r test/**/goldens/* screenshots/
          npm i
          npx reg-suit run
          rm -rf .reg/expected/
          mv -f .reg/actual/ .reg/expected/

      # PR branch との比較用にアップロード
      - name: Upload .reg/
        uses: actions/upload-artifact@v3
        with:
          name: reg-expected
          path: .reg/

  # PR branch のスクリーンショットを取得して Base branch のものと比較
  reg-suit-run:
    name: Run reg-suit
    needs: reg-suit-prepare
    if: |
      (github.event.action == 'opened') ||
      (github.event.issue.pull_request && github.event.comment.body == '/vrt')
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Tokyo'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Base branch のスクリーンショットを取得
      - name: Download reg-suit from base branch
        uses: actions/download-artifact@v3
        with:
          name: reg-expected
          path: .reg/

      - name: Use Node.js v16
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: npm install, build, and test
        run: |
          npm i

      - name: workaround for detached HEAD
        run: |
          git checkout ${{github.head_ref}} && git pull

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.2'

      - name: Install dependencies
        run: flutter pub get

      - name: touch file
        run: touch .env

      - name: Create goldens
        run: flutter test --update-goldens --tags=golden

      - name: Copy golden files
        run: |
          mkdir -p screenshots/
          cp -r test/**/goldens/* screenshots/

      - name: run reg-suit
        run: |
          npx reg-suit run

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          folder: .reg/
          target-folder: '/pr-reg-suit/pr-${{ github.event.pull_request.number }}/'
          branch: gh-pages
          clean: false

      - name: Comment to PR when finishing to deploy
        if: steps.find-comment.outputs.comment-id == ''
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body:
                'GitHub Pages へのデプロイを開始しました！\n' +
                '反映までに 15 分ほどかかる場合があります。\n' +
                ' - https://dev-tatsuya.github.io/flutter-qiita-client/pr-reg-suit/pr-${{ github.event.pull_request.number }}/'
            })

  discard_pages:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Discard pages
        uses: rossjrw/pr-preview-action@v1.4.4
        with:
          source-dir: public/
          preview-branch: gh-pages
          umbrella-dir: pr-reg-suit
          action: remove
